FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY apps ./apps
COPY libs ./libs

RUN pip install --upgrade pip && pip install .

EXPOSE 8501

CMD ["streamlit", "run", "apps/web/streamlit_app/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
